- name: Remove node
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  
  tasks:
 

      # - name: Get file content version.md content
      #   ansible.builtin.slurp:
      #     src: "{{ nolus_git_name +'/'+ network +'/version.md' }}"
      #   register: version_output


      # - name: Get version
      #   set_fact: version="{{ version_output['content']| b64decode }}"

      - name: Remove old container if exists
        community.docker.docker_container:
          name: "{{ container_name }}"
          state: absent
      


    
      - name: Prune everything
        community.docker.docker_prune:
          containers: true
          images: true
          images_filters:
            dangling: false
          networks: true
          volumes: true
          builder_cache: true

      - name: Remove Git directory
        ansible.builtin.file:
          path: "{{nolus_git_name}}/"
          state: absent

      




