- name: Update Nolus 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  
  tasks:
    
      
      - name: Get infos on container
        docker_container_info:
          name: "{{ container_name }}"
        register: result

      - name: Validate if container exist
        assert:
          that: 
            - result.exists
          fail_msg: "Container is not exist!!!"

      - name: Git checkout
        ansible.builtin.git:
          repo: '{{ nolus_git_link }}'
          dest: "{{ nolus_git_name }}/"
          force: true

      - name: Get file content version.md content
        ansible.builtin.slurp:
          src: "{{ nolus_git_name +'/'+ network +'/version.md' }}"
        register: version_output

      - name: Get version
        set_fact: version="{{ version_output['content']| b64decode }}"



      - block: 

          - name: Do domething for Update
            ansible.builtin.debug:
              msg: "Doing something for update"

          - name: Remove old container if exists
            community.docker.docker_container:
              name: "{{ container_name }}"
              state: absent

          - name: Remove image
            community.docker.docker_image:
              state: absent
              name: "{{ image_name }}"
              tag: "{{ version }}"
                    
          - name: Build the new image and with build args
            community.docker.docker_image:
              name: "{{ image_name }}"
              tag: "{{ version }}"
              state: present
              force_absent: true
              build:
                path: "{{ nolus_git_name }}/"
                dockerfile: "{{ dockerfile }}"
                args:
                  NETWORK: "{{ network }}"
                  VERSION: "{{ version }}"
              source: build

          - name: Start the container 
            community.docker.docker_container:
              name: "{{ container_name }}"
              image: "{{ image_name }}:{{ version }}"
              labels: 
                version: "{{version}}"
              pull: false
              detach: yes
              restart_policy: unless-stopped
              networks: 
                - name: "{{ network_name }}"
              volumes: 
                - "{{ volume_name }}:{{ container_mount_point }}"
              cpus: "{{ cpus }}"
              cpu_shares: "{{ cpu_shares }}"
              memory: "{{ memory }}"
              memory_reservation: "{{ memory_reservation }}"





        when: version != result.container['Config']['Labels']['version']

      - name: Print information about container
        debug:
          msg: "No new version for container"  
        when: version == result.container['Config']['Labels']['version']  