- name: Run nolus-networks validator setup
  vars_files: 
    - vars/vars.yml
    
  hosts: "{{ host }}"
  gather_facts: no
  become: yes


  tasks:
  
    # - name: Get file content version.md content
    #   ansible.builtin.slurp:
    #     src: "{{ nolus_git_name +'/'+ network +'/version.md' }}"
    #   register: version_output

    # - name: Get version
    #   set_fact: version="{{ version_output['content']| b64decode }}"
      

    - name: Get sync status inside container
      community.docker.docker_container_exec: 
        container: "{{ container_name }}"
        command: sh -c "curl http://localhost:26657/status | jq .result.sync_info.catching_up"
      register: sync_out


    - name: Validate whether the node synced
      assert:
        that: 
          - sync_out.stdout == "false"
        fail_msg: "The node is not synced!!!! Please wait for a while"

    - name: Upgrade to a Validator
      community.docker.docker_container_exec: 
        container: "{{ container_name }}"
        command: sh -c ' printf "%s\n" {{ password4key }} | nolusd tx staking create-validator --amount 1000000unls --commission-rate "0.1" --commission-max-rate "0.20" --commission-max-change-rate "0.1" --min-self-delegation "1" --pubkey=$(nolusd tendermint show-validator)  --moniker {{moniker_out.stdout}} --chain-id "nolus-rila" --gas-prices 0.0042unls --from {{keyname}} --yes'
      register: out_validator
      

    - name: Print all details about Validator result
      ansible.builtin.debug:
        var: out_validator

        

