- name: Run nolus-networks setup
  vars_files: 
    - vars/vars.yml
    
  hosts: localhost
  gather_facts: no
  become: yes

  
  tasks:

    - name: Git checkout
      ansible.builtin.git:
        repo: '{{ nolus_git_link }}'
        dest: "{{ nolus_git_name }}/"
    
    - name: Get version
      set_fact: version="{{ lookup('file', nolus_git_name +'/'+ network +'/version.md') }}"

    - name: Set image name
      set_fact: image_name="nolus-image-{{version}}"

    - name: Build image and with build args
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ dockertag }}"
        state: present
        force_absent: true
        build:
          path: "{{ nolus_git_name }}/"
          dockerfile: "{{ dockerfile }}"
          args:
            NETWORK: "{{ network }}"
            VERSION: "{{ version }}"
        source: build

    - name: Create a docker network
      docker_network:
        name: "{{ network_name }}"


    - name: Start the container 
      community.docker.docker_container:
        name: "{{ container_name }}-{{ version }}"
        image: "{{ image_name }}/{{ dockertag }}"
        detach: yes
        restart_policy: unless-stopped
        networks: 
          - name: "{{ network_name }}"
        volumes: 
          - "{{ volume_name }}:{{ container_mount_point }}"
        cpus: "{{ cpus }}"
        cpu_shares: "{{ cpu_shares }}"




    - ansible.builtin.debug:
         var: image_name
      
