- name: Run nolus-networks validator setup
  vars_files: 
    - vars/vars.yml
    
  hosts: "{{ host }}"
  gather_facts: no
  become: yes

  
  tasks:

    
    - name: Get version
      set_fact: version="{{ lookup('file', nolus_git_name +'/'+ network +'/version.md') }}"

    - name: Set image name
      set_fact: image_name="nolus-image-{{version}}"

   
    - name: Run test cmd inside container
      community.docker.docker_container_exec: 
        container: "{{ container_name }}-{{ version }}"
        command: sh -c " printf "%s\n%s\n" {{ password4key }} {{ password4key }} | nolusd keys add {{ keyname }}"
      register: out

        




    - ansible.builtin.debug:
        var: out
      
