- name: Run nolus-networks setup
  vars_files: 
    - vars/vars.yml
    
  hosts: localhost
  gather_facts: no
  become: yes

  
  tasks:

    - name: Git checkout
      ansible.builtin.git:
        repo: '{{ nolus_git_link }}'
        dest: "{{ nolus_git_name }}/"
    
    - name: Get version
      set_fact: version="{{ lookup('file', nolus_git_name +'/'+ network +'/version.md') }}"

    - name: Set image name
      set_fact: image_name="nolus-image-{{version}}"

    - name: Build image and with build args
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ dockertag }}"
        state: present
        build:
          path: "{{ nolus_git_name }}/"
          dockerfile: "{{ dockerfile }}"
          args:
            NETWORK: "{{ network }}"
            VERSION: "{{ version }}"
        source: build



    - ansible.builtin.debug:
         var: image_name
      
