- name: Update Nolus 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  
  tasks:
    
      
      - name: Get infos on container
        docker_container_info:
          name: "{{ container_name }}"
        register: result

      - name: Validate if container exist``
        assert:
          that: 
            - result.exists
          fail_msg: "Container is not exist!!!"

      - name: Print all details about recover key
        ansible.builtin.debug:
          var: result.container['Config']['Labels']['version']

      - name: Git checkout
        ansible.builtin.git:
          repo: '{{ nolus_git_link }}'
          dest: "{{ nolus_git_name }}/"
          force: true

      - name: Get file content version.md content
        ansible.builtin.slurp:
          src: "{{ nolus_git_name +'/'+ network +'/version.md' }}"
        register: version_output

      - name: Print all details about recover key
        ansible.builtin.debug:
          var: version_output['content']| b64decode


      - block: 

          - name: Do domething for Update
            ansible.builtin.debug:
              msg: "Doing something for update"

        when: (version_output['content']| b64decode) != result.container['Config']['Labels']['version']

      - name: Print information about container
        debug:
          msg: "No new version for container"  
        when: (version_output['content']| b64decode) == result.container['Config']['Labels']['version']  