- name: Update Nolus 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    
  
  tasks:
    
      
      - name: Get infos on container
        docker_container_info:
          name: "{{ container_name }}"
        register: result

      - name: Validate if container exist
        assert:
          that: 
            - result.exists
          fail_msg: "Container is not exist!!!"

      - name: Git checkout
        ansible.builtin.git:
          repo: '{{ nolus_git_link }}'
          dest: "{{ nolus_git_name }}/"
          force: true

      - name: Get file content version.md content
        ansible.builtin.slurp:
          src: "{{ nolus_git_name +'/'+ network +'/version.md' }}"
        register: version_output

      - name: Get version
        set_fact: version="{{ version_output['content']| b64decode }}"



      - block: 

          - name: Do domething for Update
            ansible.builtin.debug:
              msg: "Doing something for update"
          
          - name: Build the new image and with build args
            community.docker.docker_image:
              name: "{{ image_name }}"
              tag: "{{ version }}"
              state: present
              force_absent: true
              build:
                path: "{{ nolus_git_name }}/"
                dockerfile: "{{ dockerfile }}"
                args:
                  NETWORK: "{{ network }}"
                  VERSION: "{{ version }}"
              source: build


        when: version == result.container['Config']['Labels']['version']

      - name: Print information about container
        debug:
          msg: "No new version for container"  
        when: version == result.container['Config']['Labels']['version']  